name: Test PHPCS
on: [push, pull_request]
jobs: 
  demo: 
    name: Test 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

      
    - name: Installer PHPCS
      run: composer global require "squizlabs/php_codesniffer=*"

      
    - name: tester PHPCS sur MesDates.php
      run: ~/.composer/vendor/bin/phpcs ./src

      
    - name: afficher date de demain
      run: |
        php ./src/MesDates.php

    - name: test unitaire sur MesDates.php
      run: php C:\Users\Théo\PHP-L2\php\vendor\bin\phpunit C:\Users\Théo\PHP-L2\php\tests\MesDatesTest.php