name: Code Quality Action

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Checkout Repository Code
        uses: actions/checkout@v2

      - name: Download phpcs.phar
        uses: actions/download-artifact@v2
        with:
          name: phpcs  # Assuming you have a previously uploaded phpcs artifact

      - name: Run phpcs (assuming standard file is in test/phpcs/Symfony)
        run: php phpcs.phar --standard=test/phpcs/Symfony src

